# Generated by Django 5.1 on 2024-11-02 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attribution",
            name="heure_debut",
            field=models.TimeField(default="00:00"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="attribution",
            name="heure_fin",
            field=models.TimeField(default="00:00"),
            preserve_default=False,
        ),
    ]
