# Generated by Django 5.1 on 2024-11-04 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0002_attribution_heure_debut_attribution_heure_fin"),
    ]

    operations = [
        migrations.AddField(
            model_name="attribution",
            name="conflit_non_resolu",
            field=models.BooleanField(default=False),
        ),
    ]
